---
# This cluster is the only one to track container registry
# Use the CRD ImageRepository to track your image
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: gateway
  namespace: flux-system
spec:
  image: onlinex/app
  interval: 1m0s
---
# Use the CRD ImagePolicy to specify which version you want to track.
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: gateway
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gateway
  policy:
    semver:
      range: '>=0.0.0'