---
# This cluster is the only one to track container registry
# Use the CRD ImageRepository to track your image
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: gateway
  namespace: flux-system
spec:
  image: onlinex/app
  interval: 1m0s
---
# Use the CRD ImagePolicy to specify which version you want to track.
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: gateway
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gateway
  policy:
    semver:
      range: '>=0.0.0'
---
# ImageUpdateAutomation runs all the policies found in its namespace at the specified interval.
# Flux will push a commit to the repository with the latest image tag that matches the podinfo policy.
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./kubernetes/apps # Path to the directory containing the manifests to be updated.
    strategy: Setters