apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress # this ingress is for the api gateway
  namespace: app
spec:
  rules:
  -  http:
       paths:
         - pathType: Prefix
           path: "/"
           backend:
             service:
               name: api # name the API service on 80 port
               port:
                 number: 80
  ingressClassName: nginx