# The .spec.selector field defines how the Deployment finds which Pods to manage.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: mywebapp
  labels:
    name: web
    app: mywebapp
spec:
  replicas: 3
  selector:
      matchLabels:
        name: web  
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web 
        image: onlinex/app:latest
        ports:
        - containerPort: 80