# targets TCP port 80 on any Pod with the app.kubernetes.io/name=gateway label.
apiVersion: v1
kind: Service
metadata:
  name: api # API service
  namespace: app # run in "app" namespace
  labels:
    name: api # Label "api" for api-ingress to find
spec:
  selector:
    name: gateway # target pods with "gateway" name label 
  type: ClusterIP
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP