apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mywebapp-ingress
  namespace: mywebapp
spec:
  rules:
  -  http:
       paths:
         - pathType: Prefix
           path: "/"
           backend:
             service:
               name: web
               port:
                 number: 80
  ingressClassName: nginx