name: ci
on:
  #push:
  #  branches:
  #  - 'main'
  #  - 'dev'
  pull_request:
    branches:
      - 'main'  # handle pull requests to the main branch
#  push:
#    branches:
#      - 'main'
#      - 'dev'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # some stats
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # checks-out our repository under $GITHUB_WORKSPACE, so our workflow can access it.
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      # Login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Emulator, test on virtual machine
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # Docker build CLI
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Build and Push
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./ # starting directory
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app:0.0.2
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/app:0.0.1
          cache-to: type=inline
      #
      - run: echo "This job's status is ${{ job.status }}."

      
