name: api-ci

on:
  pull_request:
    paths:
      - .github/workflows/api-ci.yaml
      - app/**
    branches:
      - main

  push:
    paths:
      - .github/workflows/api-ci.yaml
      - app/**
    branches:
      - main

jobs:
  k8sPolicyCheck:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: ☁️ Checkout
        uses: actions/checkout@v3
      - 
        name: 📊 Datree
        uses: datreeio/action-datree@main
        with:
          path: '**/*.yaml'
          cliArguments: '--only-k8s-files --ignore-missing-schemas'
        continue-on-error: true
      - 
        name: success
        run: exit 0

  docker:
    needs: [k8sPolicyCheck]
    runs-on: ubuntu-latest
    steps:
      -
        name: ☁️ Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # source branch of PR
          fetch-depth: 0
      - 
        name: 🔧 Version
        uses: codacy/git-version@2.5.4
        with:
          release-branch: main
          dev-branch: dev
        id: gitVersion   
      -
        name: 🔧 QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: 🔧 Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: "🔧 Cache docker layers"
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: 📦 Build & Save
        uses: docker/build-push-action@v3
        with:
          context: .
          push: False
          file: ./Dockerfile

          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app:${{ steps.gitVersion.outputs.version }}
          outputs: type=docker,dest=/tmp/api-snapshot.tar

          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
      -
        name: 📂 Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-snapshot
          path: /tmp/api-snapshot.tar
          retention-days: 1
      - 
        run: echo "New Version ${{ steps.gitVersion.outputs.version }}."

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: api-snapshot
          path: /tmp
      -
        name: Run Flake8
        continue-on-error: true
        run: |
          image_name_tag=$(docker load --input /tmp/api-snapshot.tar)
          echo "res = ${image_name_tag:14}"
          docker run -i ${image_name_tag:14} poetry run flake8
      - 
        name: Run SUCCESS script
        run: exit 0

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: api-snapshot
          path: /tmp
      -
        name: Run Pytest
        continue-on-error: true
        run: |
          image_name_tag=$(docker load --input /tmp/api-snapshot.tar)
          echo "res = ${image_name_tag:14}"
          docker run -i ${image_name_tag:14} poetry run pytest
      - 
        name: Run SUCCESS script
        run: exit 0

  deploy:
    if: ${{ github.event_name != 'pull_request' }} # if push to main (anyhow)
    runs-on: ubuntu-latest
    steps:
      - # checks-out our repository under $GITHUB_WORKSPACE, so our workflow can access it.
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the source branch of the pull request in a workflow run
          fetch-depth: 0                # fetch the whole repo history
      - 
        name: Git Version
        uses: codacy/git-version@2.5.4
        id: gitVersion
        with:
          release-branch: main
          dev-branch: dev
      - # Login to docker hub
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - # Emulator, binaries for different hardware
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - # Docker build CLI
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - # Build and Push
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./ # starting directory
          file: ./Dockerfile
          push: True # don't push on pull request (in testing phase) ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app:${{ steps.gitVersion.outputs.version }}
          cache-from: type=gha
      - 
        run: echo "New Version ${{ steps.gitVersion.outputs.version }}."
      - 
        run: echo "This job's status is ${{ job.status }}."

  cleanup:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: "♻️ remove build artifacts"
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            api-snapshot
          failOnError: false